project:
  type: website
  output-dir: docs

website:
  site-url: "https://alirezach.github.io/persian"
  title: "تحلیل داده با علی‌رضا"
  reader-mode: true
  open-graph: true
  twitter-card: 
    site: "@alirezach"
  navbar:
    left:
      - text: صفحه اصلی
        href: https://alirezach.github.io
      - text: وبلاگ
        href: index.qmd
      - icon: rss
        href: index.xml
#      - about.qmd
      - icon: linkedin
        href: https://www.linkedin.com/in/alirezachamanzar/
      - icon: twitter
        href: https://x.com/alirezach
      - icon: github
        menu:
          - text: سورس کد
            url:  https://github.com/alirezach/persian
          - text: مشکلات را گزارش دهید
            url:  https://github.com/alirezach/persian/issues
  page-footer:
    border: false
    right: "©[علیرضا چمن‌زار](https://github.com/alirezach) 1403~"
    left: "ساخته شده با R و کوارتو بر بستر گیتهاب"

format:
  html:
    theme:
      light: Litera
      dark:  Cyborg
    css: fa.css
language: fa.yml
editor: visual

