project:
  type: website
  output-dir: docs

website:
  title: "تحلیل داده با علی‌رضا"
  navbar:
    left:
      - text: صفحه اصلی
        href: https://alirezach.github.io
      - text: وبلاگ
        href: index.qmd
#      - about.qmd
      - icon: linkedin
        href: https://www.linkedin.com/in/alirezachamanzar/
      - icon: twitter
        href: https://x.com/alirezach
      - icon: github
        menu:
          - text: سورس کد
            url:  https://github.com/alirezach/persian
          - text: مشکلات را گزارش دهید
            url:  https://github.com/alirezach/persian/issues
  page-footer:
    border: false
    right: "©[علیرضا چمن‌زار](https://github.com/alirezach) 1403~"
    left: "ساخته شده با R و کوارتو بر بستر گیتهاب"

format:
  html:
    theme:
      light: sandstone
      dark: sandstone
    css: fa.css
language: fa.yml
editor: visual

